#!/usr/bin/env python3
"""
gen_connections.py - generate _FeatureConnection boilerplate from a YAML spec.

Run from software/frontend/:
    python scripts/gen_connections.py \\
        src/rxn_bench_ui/devices/<devicename>/<devicename>.yaml \\
        --out src/rxn_bench_ui/devices/<devicename>/generated_connection.py

What it generates (per spec):
    - Qt Signal declarations for each stream observable
    - _rpc() helper
    - _on_connected() with _spawn_stream() calls
    - _after_connected() hook (no-op; override in subclass for post-connect logic)
    - Abstract stubs for "handler" streams (NotImplementedError)
    - Typed command methods with protobuf parameter construction

What it does NOT generate:
    - Widget code or UX logic
    - Dataclass definitions
    - Blocking fetch methods
    - Custom convenience methods
    - Error messages intended for humans
    - Higher-level workflows

Add all of the above in the human subclass (devices/<name>/connection.py).
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml


# ---------------------------------------------------------------------------
# Stream helpers
# ---------------------------------------------------------------------------

def _signal_type_str(args: list) -> str:
    return ", ".join(str(a) for a in args)


def _spawn_call_lines(s: dict) -> list[str]:
    rpc         = s["rpc"]
    decode_type = s.get("decode_type")      # None → raw bytes, no decode= kwarg

    if "handler" in s:
        handler_expr = f"self.{s['handler']}"
    else:
        emits = s["emit"]
        if len(emits) == 1:
            handler_expr = f"lambda r: self.{s['signal']}.emit({emits[0]})"
        else:
            handler_expr = f"lambda r: self.{s['signal']}.emit({', '.join(emits)})"

    lines = [
        f"        self._spawn_stream(",
        f"            gen, self._rpc(\"{rpc}\"),",
        f"            {handler_expr},",
    ]
    if decode_type:
        lines.append(f"            decode=_pb.{decode_type}.FromString,")
    # else: omit → _spawn_stream default is decode=bytes (raw)
    lines.append("        )")
    return lines


# ---------------------------------------------------------------------------
# Command helpers
# ---------------------------------------------------------------------------

def _command_lines(cmd: dict) -> list[str]:
    method = cmd["method"]
    rpc    = cmd["rpc"]
    params = cmd.get("params")
    args   = cmd.get("args", [])

    if args:
        sig_parts = []
        for arg in args:
            if "default" in arg:
                sig_parts.append(f"{arg['name']}: {arg['type']} = {arg['default']}")
            else:
                sig_parts.append(f"{arg['name']}: {arg['type']}")
        sig = f"    def {method}(self, {', '.join(sig_parts)}) -> None:"
    else:
        sig = f"    def {method}(self) -> None:"

    body: list[str] = []
    if params:
        body.append(f"        _p = _pb.{params}()")
        for arg in args:
            body.append(f"        _p.{arg['field']}.value = {arg['name']}")
        body.append(f"        self._fire(self._rpc(\"{rpc}\"), _p.SerializeToString())")
    else:
        body.append(f"        self._fire(self._rpc(\"{rpc}\"))")

    return [sig] + body


# ---------------------------------------------------------------------------
# Top-level generator
# ---------------------------------------------------------------------------

def generate(spec: dict, spec_path: str, out_path: str | None = None) -> str:
    meta     = spec["meta"]
    pkg      = meta["package"]
    svc      = meta["service"]
    cls      = meta["class_name"]
    pb2_mod  = meta.get("proto_module")   # None → no compiled stubs, no _pb import
    streams  = spec.get("streams", [])
    commands = spec.get("commands", [])
    spec_name = Path(spec_path).name
    # Default output: generated_connection.py alongside the spec
    spec_dir = Path(spec_path).parent
    out_name = out_path or str(spec_dir / "generated_connection.py")

    out: list[str] = []

    # ------------------------------------------------------------------
    # Header
    # ------------------------------------------------------------------
    out += [
        "# fmt: off",
        "# Generated by scripts/gen_connections.py - do not edit by hand.",
        f"# Source: {spec_path}",
        "# Regenerate (from software/frontend/):",
        f"#   python scripts/gen_connections.py {spec_path}",
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "",
        "from PySide6.QtCore import Signal",
        "",
        "from rxn_bench_ui.connections.base import _FeatureConnection",
    ]
    if pb2_mod:
        out.append(f"import {pb2_mod} as _pb")
    out += [
        "",
        "",
        f'_PKG = "{pkg}"',
        f'_SVC = "{svc}"',
        "",
        "",
        f"class {cls}(_FeatureConnection):",
        '    """',
        f"    Generated connection base for the {svc} SiLA feature.",
        "    Do not edit - subclass this to add custom handlers and higher-level methods.",
        '    """',
        "",
    ]

    # ------------------------------------------------------------------
    # Signal declarations
    # ------------------------------------------------------------------
    out.append("    # --- Observable signals ---")
    for s in streams:
        out.append(f"    {s['signal']} = Signal({_signal_type_str(s['signal_args'])})")
    out.append("")

    # ------------------------------------------------------------------
    # _rpc helper
    # ------------------------------------------------------------------
    out += [
        "    def _rpc(self, name: str) -> str:",
        '        return f"/{_PKG}.{_SVC}/{name}"',
        "",
    ]

    # ------------------------------------------------------------------
    # _on_connected
    # ------------------------------------------------------------------
    out.append("    def _on_connected(self, gen: int) -> None:")
    for s in streams:
        out += _spawn_call_lines(s)
        out.append("")
    out.append("        self._after_connected(gen)")
    out.append("")

    # ------------------------------------------------------------------
    # _after_connected hook
    # ------------------------------------------------------------------
    out += [
        "    def _after_connected(self, gen: int) -> None:",
        '        """Override in subclass to run post-connect logic (e.g. blocking fetches)."""',
        "",
    ]

    # ------------------------------------------------------------------
    # Abstract stubs for custom stream handlers
    # ------------------------------------------------------------------
    custom_handlers = [s["handler"] for s in streams if "handler" in s]
    if custom_handlers:
        out.append("    # --- Custom stream handlers - implement in subclass ---")
        for h in custom_handlers:
            out += [
                f"    def {h}(self, resp: Any) -> None:",
                f'        raise NotImplementedError("{h} must be implemented in subclass")',
                "",
            ]

    # ------------------------------------------------------------------
    # Commands
    # ------------------------------------------------------------------
    out.append("    # --- Commands ---")
    for cmd in commands:
        out += _command_lines(cmd)
        out.append("")

    return "\n".join(out)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("spec", help="Path to the YAML spec file")
    parser.add_argument("--out", help="Output file (default: stdout)")
    args = parser.parse_args()

    spec_path = Path(args.spec)
    if not spec_path.exists():
        print(f"error: spec not found: {spec_path}", file=sys.stderr)
        sys.exit(1)

    with open(spec_path) as f:
        spec = yaml.safe_load(f)

    code = generate(spec, args.spec, out_path=args.out)

    # Default output: generated_connection.py alongside the spec
    resolved_out = Path(args.out) if args.out else Path(args.spec).parent / "generated_connection.py"
    resolved_out.parent.mkdir(parents=True, exist_ok=True)
    resolved_out.write_text(code + "\n")
    print(f"Generated {resolved_out}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    main()
